// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error struct {
	OK                   bool     `protobuf:"varint,2,opt,name=OK,proto3" json:"OK,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetOK() bool {
	if m != nil {
		return m.OK
	}
	return false
}

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type InitRequest struct {
	EventServer          uint32   `protobuf:"varint,1,opt,name=event_server,json=eventServer,proto3" json:"event_server,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1}
}

func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (m *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(m, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

func (m *InitRequest) GetEventServer() uint32 {
	if m != nil {
		return m.EventServer
	}
	return 0
}

func (m *InitRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type OnCreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config               []byte   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnCreateRequest) Reset()         { *m = OnCreateRequest{} }
func (m *OnCreateRequest) String() string { return proto.CompactTextString(m) }
func (*OnCreateRequest) ProtoMessage()    {}
func (*OnCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{2}
}

func (m *OnCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnCreateRequest.Unmarshal(m, b)
}
func (m *OnCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnCreateRequest.Marshal(b, m, deterministic)
}
func (m *OnCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnCreateRequest.Merge(m, src)
}
func (m *OnCreateRequest) XXX_Size() int {
	return xxx_messageInfo_OnCreateRequest.Size(m)
}
func (m *OnCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnCreateRequest proto.InternalMessageInfo

func (m *OnCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OnCreateRequest) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

type OnCreateResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnCreateResponse) Reset()         { *m = OnCreateResponse{} }
func (m *OnCreateResponse) String() string { return proto.CompactTextString(m) }
func (*OnCreateResponse) ProtoMessage()    {}
func (*OnCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{3}
}

func (m *OnCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnCreateResponse.Unmarshal(m, b)
}
func (m *OnCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnCreateResponse.Marshal(b, m, deterministic)
}
func (m *OnCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnCreateResponse.Merge(m, src)
}
func (m *OnCreateResponse) XXX_Size() int {
	return xxx_messageInfo_OnCreateResponse.Size(m)
}
func (m *OnCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OnCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OnCreateResponse proto.InternalMessageInfo

func (m *OnCreateResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type OnMessageRequest struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	InMessage            []byte   `protobuf:"bytes,2,opt,name=inMessage,proto3" json:"inMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnMessageRequest) Reset()         { *m = OnMessageRequest{} }
func (m *OnMessageRequest) String() string { return proto.CompactTextString(m) }
func (*OnMessageRequest) ProtoMessage()    {}
func (*OnMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{4}
}

func (m *OnMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnMessageRequest.Unmarshal(m, b)
}
func (m *OnMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnMessageRequest.Marshal(b, m, deterministic)
}
func (m *OnMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnMessageRequest.Merge(m, src)
}
func (m *OnMessageRequest) XXX_Size() int {
	return xxx_messageInfo_OnMessageRequest.Size(m)
}
func (m *OnMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnMessageRequest proto.InternalMessageInfo

func (m *OnMessageRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *OnMessageRequest) GetInMessage() []byte {
	if m != nil {
		return m.InMessage
	}
	return nil
}

type OnMessageResponse struct {
	OutMessage           []byte   `protobuf:"bytes,1,opt,name=outMessage,proto3" json:"outMessage,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnMessageResponse) Reset()         { *m = OnMessageResponse{} }
func (m *OnMessageResponse) String() string { return proto.CompactTextString(m) }
func (*OnMessageResponse) ProtoMessage()    {}
func (*OnMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{5}
}

func (m *OnMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnMessageResponse.Unmarshal(m, b)
}
func (m *OnMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnMessageResponse.Marshal(b, m, deterministic)
}
func (m *OnMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnMessageResponse.Merge(m, src)
}
func (m *OnMessageResponse) XXX_Size() int {
	return xxx_messageInfo_OnMessageResponse.Size(m)
}
func (m *OnMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OnMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OnMessageResponse proto.InternalMessageInfo

func (m *OnMessageResponse) GetOutMessage() []byte {
	if m != nil {
		return m.OutMessage
	}
	return nil
}

func (m *OnMessageResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type OnCloseRequest struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnCloseRequest) Reset()         { *m = OnCloseRequest{} }
func (m *OnCloseRequest) String() string { return proto.CompactTextString(m) }
func (*OnCloseRequest) ProtoMessage()    {}
func (*OnCloseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{6}
}

func (m *OnCloseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnCloseRequest.Unmarshal(m, b)
}
func (m *OnCloseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnCloseRequest.Marshal(b, m, deterministic)
}
func (m *OnCloseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnCloseRequest.Merge(m, src)
}
func (m *OnCloseRequest) XXX_Size() int {
	return xxx_messageInfo_OnCloseRequest.Size(m)
}
func (m *OnCloseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OnCloseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OnCloseRequest proto.InternalMessageInfo

func (m *OnCloseRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

type OnCloseResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnCloseResponse) Reset()         { *m = OnCloseResponse{} }
func (m *OnCloseResponse) String() string { return proto.CompactTextString(m) }
func (*OnCloseResponse) ProtoMessage()    {}
func (*OnCloseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{7}
}

func (m *OnCloseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnCloseResponse.Unmarshal(m, b)
}
func (m *OnCloseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnCloseResponse.Marshal(b, m, deterministic)
}
func (m *OnCloseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnCloseResponse.Merge(m, src)
}
func (m *OnCloseResponse) XXX_Size() int {
	return xxx_messageInfo_OnCloseResponse.Size(m)
}
func (m *OnCloseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OnCloseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OnCloseResponse proto.InternalMessageInfo

func (m *OnCloseResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{8}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type DebugRequest struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Message              []byte   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebugRequest) Reset()         { *m = DebugRequest{} }
func (m *DebugRequest) String() string { return proto.CompactTextString(m) }
func (*DebugRequest) ProtoMessage()    {}
func (*DebugRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{9}
}

func (m *DebugRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugRequest.Unmarshal(m, b)
}
func (m *DebugRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugRequest.Marshal(b, m, deterministic)
}
func (m *DebugRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugRequest.Merge(m, src)
}
func (m *DebugRequest) XXX_Size() int {
	return xxx_messageInfo_DebugRequest.Size(m)
}
func (m *DebugRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DebugRequest proto.InternalMessageInfo

func (m *DebugRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *DebugRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DebugRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type EmitFlowEventRequest struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmitFlowEventRequest) Reset()         { *m = EmitFlowEventRequest{} }
func (m *EmitFlowEventRequest) String() string { return proto.CompactTextString(m) }
func (*EmitFlowEventRequest) ProtoMessage()    {}
func (*EmitFlowEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{10}
}

func (m *EmitFlowEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmitFlowEventRequest.Unmarshal(m, b)
}
func (m *EmitFlowEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmitFlowEventRequest.Marshal(b, m, deterministic)
}
func (m *EmitFlowEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmitFlowEventRequest.Merge(m, src)
}
func (m *EmitFlowEventRequest) XXX_Size() int {
	return xxx_messageInfo_EmitFlowEventRequest.Size(m)
}
func (m *EmitFlowEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmitFlowEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmitFlowEventRequest proto.InternalMessageInfo

func (m *EmitFlowEventRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *EmitFlowEventRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EmitOutputRequest struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Output               []byte   `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmitOutputRequest) Reset()         { *m = EmitOutputRequest{} }
func (m *EmitOutputRequest) String() string { return proto.CompactTextString(m) }
func (*EmitOutputRequest) ProtoMessage()    {}
func (*EmitOutputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{11}
}

func (m *EmitOutputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmitOutputRequest.Unmarshal(m, b)
}
func (m *EmitOutputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmitOutputRequest.Marshal(b, m, deterministic)
}
func (m *EmitOutputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmitOutputRequest.Merge(m, src)
}
func (m *EmitOutputRequest) XXX_Size() int {
	return xxx_messageInfo_EmitOutputRequest.Size(m)
}
func (m *EmitOutputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmitOutputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmitOutputRequest proto.InternalMessageInfo

func (m *EmitOutputRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *EmitOutputRequest) GetOutput() []byte {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *EmitOutputRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type EmitErrorRequest struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmitErrorRequest) Reset()         { *m = EmitErrorRequest{} }
func (m *EmitErrorRequest) String() string { return proto.CompactTextString(m) }
func (*EmitErrorRequest) ProtoMessage()    {}
func (*EmitErrorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{12}
}

func (m *EmitErrorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmitErrorRequest.Unmarshal(m, b)
}
func (m *EmitErrorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmitErrorRequest.Marshal(b, m, deterministic)
}
func (m *EmitErrorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmitErrorRequest.Merge(m, src)
}
func (m *EmitErrorRequest) XXX_Size() int {
	return xxx_messageInfo_EmitErrorRequest.Size(m)
}
func (m *EmitErrorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmitErrorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmitErrorRequest proto.InternalMessageInfo

func (m *EmitErrorRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *EmitErrorRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EmitErrorRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetVaultItemRequest struct {
	VaultId              string   `protobuf:"bytes,1,opt,name=vaultId,proto3" json:"vaultId,omitempty"`
	ItemId               string   `protobuf:"bytes,2,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVaultItemRequest) Reset()         { *m = GetVaultItemRequest{} }
func (m *GetVaultItemRequest) String() string { return proto.CompactTextString(m) }
func (*GetVaultItemRequest) ProtoMessage()    {}
func (*GetVaultItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{13}
}

func (m *GetVaultItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVaultItemRequest.Unmarshal(m, b)
}
func (m *GetVaultItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVaultItemRequest.Marshal(b, m, deterministic)
}
func (m *GetVaultItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVaultItemRequest.Merge(m, src)
}
func (m *GetVaultItemRequest) XXX_Size() int {
	return xxx_messageInfo_GetVaultItemRequest.Size(m)
}
func (m *GetVaultItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVaultItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVaultItemRequest proto.InternalMessageInfo

func (m *GetVaultItemRequest) GetVaultId() string {
	if m != nil {
		return m.VaultId
	}
	return ""
}

func (m *GetVaultItemRequest) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

type GetVaultItemResponse struct {
	Item                 *_struct.Struct `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetVaultItemResponse) Reset()         { *m = GetVaultItemResponse{} }
func (m *GetVaultItemResponse) String() string { return proto.CompactTextString(m) }
func (*GetVaultItemResponse) ProtoMessage()    {}
func (*GetVaultItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{14}
}

func (m *GetVaultItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVaultItemResponse.Unmarshal(m, b)
}
func (m *GetVaultItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVaultItemResponse.Marshal(b, m, deterministic)
}
func (m *GetVaultItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVaultItemResponse.Merge(m, src)
}
func (m *GetVaultItemResponse) XXX_Size() int {
	return xxx_messageInfo_GetVaultItemResponse.Size(m)
}
func (m *GetVaultItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVaultItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVaultItemResponse proto.InternalMessageInfo

func (m *GetVaultItemResponse) GetItem() *_struct.Struct {
	if m != nil {
		return m.Item
	}
	return nil
}

type Variable struct {
	Scope                string   `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Variable) Reset()         { *m = Variable{} }
func (m *Variable) String() string { return proto.CompactTextString(m) }
func (*Variable) ProtoMessage()    {}
func (*Variable) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{15}
}

func (m *Variable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Variable.Unmarshal(m, b)
}
func (m *Variable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Variable.Marshal(b, m, deterministic)
}
func (m *Variable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Variable.Merge(m, src)
}
func (m *Variable) XXX_Size() int {
	return xxx_messageInfo_Variable.Size(m)
}
func (m *Variable) XXX_DiscardUnknown() {
	xxx_messageInfo_Variable.DiscardUnknown(m)
}

var xxx_messageInfo_Variable proto.InternalMessageInfo

func (m *Variable) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *Variable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetVariableRequest struct {
	Variable             *Variable `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetVariableRequest) Reset()         { *m = GetVariableRequest{} }
func (m *GetVariableRequest) String() string { return proto.CompactTextString(m) }
func (*GetVariableRequest) ProtoMessage()    {}
func (*GetVariableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{16}
}

func (m *GetVariableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVariableRequest.Unmarshal(m, b)
}
func (m *GetVariableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVariableRequest.Marshal(b, m, deterministic)
}
func (m *GetVariableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVariableRequest.Merge(m, src)
}
func (m *GetVariableRequest) XXX_Size() int {
	return xxx_messageInfo_GetVariableRequest.Size(m)
}
func (m *GetVariableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVariableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVariableRequest proto.InternalMessageInfo

func (m *GetVariableRequest) GetVariable() *Variable {
	if m != nil {
		return m.Variable
	}
	return nil
}

type GetVariableResponse struct {
	Value                *_struct.Struct `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetVariableResponse) Reset()         { *m = GetVariableResponse{} }
func (m *GetVariableResponse) String() string { return proto.CompactTextString(m) }
func (*GetVariableResponse) ProtoMessage()    {}
func (*GetVariableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{17}
}

func (m *GetVariableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVariableResponse.Unmarshal(m, b)
}
func (m *GetVariableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVariableResponse.Marshal(b, m, deterministic)
}
func (m *GetVariableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVariableResponse.Merge(m, src)
}
func (m *GetVariableResponse) XXX_Size() int {
	return xxx_messageInfo_GetVariableResponse.Size(m)
}
func (m *GetVariableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVariableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVariableResponse proto.InternalMessageInfo

func (m *GetVariableResponse) GetValue() *_struct.Struct {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetVariableRequest struct {
	Variable             *Variable       `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	Value                *_struct.Struct `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SetVariableRequest) Reset()         { *m = SetVariableRequest{} }
func (m *SetVariableRequest) String() string { return proto.CompactTextString(m) }
func (*SetVariableRequest) ProtoMessage()    {}
func (*SetVariableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{18}
}

func (m *SetVariableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVariableRequest.Unmarshal(m, b)
}
func (m *SetVariableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVariableRequest.Marshal(b, m, deterministic)
}
func (m *SetVariableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVariableRequest.Merge(m, src)
}
func (m *SetVariableRequest) XXX_Size() int {
	return xxx_messageInfo_SetVariableRequest.Size(m)
}
func (m *SetVariableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVariableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetVariableRequest proto.InternalMessageInfo

func (m *SetVariableRequest) GetVariable() *Variable {
	if m != nil {
		return m.Variable
	}
	return nil
}

func (m *SetVariableRequest) GetValue() *_struct.Struct {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "proto.Error")
	proto.RegisterType((*InitRequest)(nil), "proto.InitRequest")
	proto.RegisterType((*OnCreateRequest)(nil), "proto.OnCreateRequest")
	proto.RegisterType((*OnCreateResponse)(nil), "proto.OnCreateResponse")
	proto.RegisterType((*OnMessageRequest)(nil), "proto.OnMessageRequest")
	proto.RegisterType((*OnMessageResponse)(nil), "proto.OnMessageResponse")
	proto.RegisterType((*OnCloseRequest)(nil), "proto.OnCloseRequest")
	proto.RegisterType((*OnCloseResponse)(nil), "proto.OnCloseResponse")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*DebugRequest)(nil), "proto.DebugRequest")
	proto.RegisterType((*EmitFlowEventRequest)(nil), "proto.EmitFlowEventRequest")
	proto.RegisterType((*EmitOutputRequest)(nil), "proto.EmitOutputRequest")
	proto.RegisterType((*EmitErrorRequest)(nil), "proto.EmitErrorRequest")
	proto.RegisterType((*GetVaultItemRequest)(nil), "proto.GetVaultItemRequest")
	proto.RegisterType((*GetVaultItemResponse)(nil), "proto.GetVaultItemResponse")
	proto.RegisterType((*Variable)(nil), "proto.Variable")
	proto.RegisterType((*GetVariableRequest)(nil), "proto.GetVariableRequest")
	proto.RegisterType((*GetVariableResponse)(nil), "proto.GetVariableResponse")
	proto.RegisterType((*SetVariableRequest)(nil), "proto.SetVariableRequest")
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_22a625af4bc1cc87) }

var fileDescriptor_22a625af4bc1cc87 = []byte{
	// 722 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0x56, 0xd2, 0xb8, 0x49, 0x26, 0x4e, 0x0f, 0xdb, 0xfe, 0xa9, 0x7f, 0x17, 0xa1, 0xb2, 0x70,
	0x11, 0x51, 0x91, 0x8b, 0x50, 0x2a, 0x04, 0xa2, 0x12, 0x6a, 0x42, 0xa9, 0x2a, 0x08, 0x72, 0x50,
	0xb9, 0x44, 0x4e, 0xba, 0xb5, 0x2c, 0xd9, 0x5e, 0x63, 0xaf, 0x83, 0x78, 0x48, 0x9e, 0x83, 0xd7,
	0x40, 0x5e, 0xef, 0xda, 0x6b, 0x27, 0x04, 0xaa, 0x5e, 0xd9, 0x3b, 0x33, 0xdf, 0x37, 0xe7, 0x01,
	0x3d, 0xf4, 0x12, 0xc7, 0x0d, 0x06, 0x61, 0x44, 0x19, 0x45, 0x1a, 0xff, 0x98, 0x7a, 0xcc, 0xa2,
	0x64, 0xce, 0x32, 0x21, 0x1e, 0x83, 0x36, 0x8e, 0x22, 0x1a, 0xa1, 0x2d, 0xa8, 0x4f, 0xae, 0x8c,
	0xfa, 0x51, 0xad, 0xdf, 0xb2, 0xea, 0x93, 0x2b, 0x84, 0xa0, 0x31, 0xa7, 0x37, 0xc4, 0xd8, 0x38,
	0xaa, 0xf5, 0xdb, 0x16, 0xff, 0x47, 0x06, 0x34, 0x7d, 0x12, 0xc7, 0xb6, 0x43, 0x8c, 0x06, 0x17,
	0xcb, 0x27, 0x1e, 0x41, 0xe7, 0x32, 0x70, 0x99, 0x45, 0xbe, 0x25, 0x24, 0x66, 0xe8, 0x11, 0xe8,
	0x64, 0x41, 0x02, 0xf6, 0x35, 0x26, 0xd1, 0x82, 0x44, 0x46, 0xed, 0xa8, 0xd6, 0xef, 0x5a, 0x1d,
	0x2e, 0x9b, 0x72, 0x51, 0xca, 0x1f, 0xd2, 0x88, 0x71, 0x8f, 0x5d, 0x8b, 0xff, 0xe3, 0x37, 0xb0,
	0x3d, 0x09, 0xce, 0x23, 0x62, 0x33, 0x22, 0x99, 0x10, 0x34, 0x02, 0xdb, 0x27, 0x9c, 0xa1, 0x6d,
	0xf1, 0x7f, 0xd4, 0x83, 0xcd, 0x39, 0x0d, 0x6e, 0x5d, 0x87, 0x83, 0x75, 0x4b, 0xbc, 0xf0, 0x29,
	0xec, 0x14, 0xf0, 0x38, 0xa4, 0x41, 0x4c, 0x10, 0x06, 0x8d, 0xa4, 0xf9, 0x71, 0x82, 0xce, 0x50,
	0xcf, 0xd2, 0x1e, 0xf0, 0x9c, 0xad, 0x4c, 0x85, 0x47, 0x29, 0xee, 0x43, 0x96, 0x89, 0xe2, 0xd7,
	0x49, 0xdc, 0x1b, 0xe9, 0x37, 0xfd, 0x47, 0x0f, 0xa0, 0xed, 0x4a, 0x3b, 0xe1, 0xba, 0x10, 0xe0,
	0x2f, 0xb0, 0xab, 0xb0, 0x08, 0xf7, 0x0f, 0x01, 0x68, 0xc2, 0x24, 0xa6, 0xc6, 0x31, 0x8a, 0xa4,
	0x08, 0xaf, 0xfe, 0xe7, 0xf0, 0x9e, 0xc0, 0xd6, 0x24, 0x38, 0xf7, 0x68, 0xbc, 0x2e, 0x38, 0xfc,
	0x82, 0xd7, 0x2e, 0xb3, 0xba, 0x43, 0xee, 0x4d, 0xd0, 0xc6, 0x7e, 0xc8, 0x7e, 0xe0, 0x4f, 0xa0,
	0x8f, 0xc8, 0x2c, 0x71, 0xd6, 0x15, 0x40, 0x36, 0xa3, 0xae, 0x34, 0x43, 0x99, 0x89, 0x0d, 0x9e,
	0x5e, 0x3e, 0x13, 0x67, 0xb0, 0x3f, 0xf6, 0x5d, 0xf6, 0xce, 0xa3, 0xdf, 0xc7, 0x69, 0xe3, 0xef,
	0xc8, 0x8c, 0xa7, 0xb0, 0x9b, 0xe2, 0x27, 0x09, 0x0b, 0x93, 0xb5, 0xe0, 0x1e, 0x6c, 0x52, 0x6e,
	0x24, 0xe7, 0x21, 0x7b, 0xe5, 0x23, 0x96, 0xc6, 0xa5, 0x89, 0x11, 0xfb, 0x0c, 0x3b, 0x29, 0x69,
	0x56, 0x83, 0xfb, 0xa5, 0xaa, 0x8c, 0xff, 0x05, 0xec, 0x5d, 0x10, 0x76, 0x6d, 0x27, 0x1e, 0xbb,
	0x64, 0xc4, 0x97, 0xc4, 0x06, 0x34, 0x17, 0x5c, 0x26, 0xb9, 0xe5, 0x33, 0x0d, 0x39, 0x35, 0xbc,
	0xbc, 0x11, 0x0e, 0xc4, 0x0b, 0x9f, 0xc3, 0x7e, 0x99, 0x48, 0xb4, 0xf2, 0x18, 0x1a, 0x2e, 0x23,
	0xbe, 0xe8, 0xe4, 0xc1, 0xc0, 0xa1, 0xd4, 0xf1, 0x48, 0xd6, 0xd0, 0x59, 0x72, 0x3b, 0x98, 0xf2,
	0x9d, 0xb6, 0xb8, 0x11, 0x3e, 0x81, 0xd6, 0xb5, 0x1d, 0xb9, 0xf6, 0xcc, 0x23, 0x68, 0x1f, 0xb4,
	0x78, 0x4e, 0x43, 0xb9, 0x40, 0xd9, 0x63, 0x65, 0xb9, 0xdf, 0x02, 0xe2, 0xae, 0x33, 0xa0, 0x4c,
	0xe1, 0x18, 0x5a, 0x0b, 0x21, 0x12, 0xce, 0xb7, 0xc5, 0x18, 0xe5, 0x96, 0xb9, 0x01, 0x1e, 0x89,
	0x32, 0x48, 0x0a, 0x11, 0xfc, 0x33, 0xd0, 0x16, 0xb6, 0x97, 0x90, 0xbf, 0x45, 0x9f, 0x59, 0xe1,
	0x10, 0xd0, 0xf4, 0x7e, 0x81, 0x14, 0x1e, 0xeb, 0xff, 0xe2, 0x71, 0xf8, 0xab, 0x06, 0x8d, 0x8f,
	0xe9, 0x81, 0xeb, 0x43, 0x23, 0x3d, 0x63, 0x08, 0x09, 0x6a, 0xe5, 0xa6, 0x99, 0xf9, 0xfa, 0xa4,
	0xeb, 0x82, 0x5e, 0x43, 0x4b, 0xde, 0x1a, 0xd4, 0x13, 0x9a, 0xca, 0xed, 0x32, 0x0f, 0x96, 0xe4,
	0xa2, 0x20, 0x67, 0xd0, 0xce, 0x4f, 0x05, 0x2a, 0xac, 0xca, 0x27, 0xc8, 0x34, 0x96, 0x15, 0x02,
	0xff, 0x12, 0x9a, 0x62, 0xd7, 0xd1, 0x7f, 0x85, 0x0f, 0xe5, 0x42, 0x98, 0xbd, 0xaa, 0x38, 0x43,
	0x0e, 0x7f, 0x6e, 0x40, 0xd7, 0x4a, 0x02, 0xe6, 0xfa, 0xe4, 0x3d, 0xf1, 0x42, 0x12, 0xa1, 0xc7,
	0xa0, 0x65, 0x4c, 0xa5, 0xfc, 0x2a, 0xd9, 0x3e, 0x05, 0x8d, 0x1f, 0x07, 0xb4, 0x27, 0xc4, 0xea,
	0xa9, 0xa8, 0xd8, 0xbe, 0x82, 0x6e, 0x69, 0xed, 0xd1, 0x61, 0xae, 0x5e, 0x3e, 0x06, 0x15, 0xec,
	0x09, 0x40, 0xb1, 0xf2, 0xc8, 0x50, 0x80, 0xa5, 0x2b, 0x50, 0x41, 0x0d, 0xa1, 0x9d, 0xef, 0x74,
	0x5e, 0xce, 0xea, 0x96, 0x57, 0x30, 0x17, 0xa0, 0xab, 0x8b, 0x86, 0x4c, 0xa1, 0x5d, 0xb1, 0xc6,
	0xe6, 0xe1, 0x4a, 0x9d, 0xe8, 0xc5, 0x08, 0x3a, 0xca, 0xcc, 0xa3, 0xff, 0x55, 0xdb, 0xd2, 0x04,
	0x9b, 0xe6, 0x2a, 0x95, 0x60, 0x39, 0x85, 0xce, 0x74, 0x05, 0xcb, 0xf2, 0x1e, 0x94, 0xd3, 0x98,
	0x6d, 0xf2, 0xc7, 0xf3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x36, 0x49, 0xb6, 0xea, 0x07,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*Empty, error)
	OnCreate(ctx context.Context, in *OnCreateRequest, opts ...grpc.CallOption) (*OnCreateResponse, error)
	OnMessage(ctx context.Context, in *OnMessageRequest, opts ...grpc.CallOption) (*OnMessageResponse, error)
	OnClose(ctx context.Context, in *OnCloseRequest, opts ...grpc.CallOption) (*OnCloseResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Node/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) OnCreate(ctx context.Context, in *OnCreateRequest, opts ...grpc.CallOption) (*OnCreateResponse, error) {
	out := new(OnCreateResponse)
	err := c.cc.Invoke(ctx, "/proto.Node/OnCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) OnMessage(ctx context.Context, in *OnMessageRequest, opts ...grpc.CallOption) (*OnMessageResponse, error) {
	out := new(OnMessageResponse)
	err := c.cc.Invoke(ctx, "/proto.Node/OnMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) OnClose(ctx context.Context, in *OnCloseRequest, opts ...grpc.CallOption) (*OnCloseResponse, error) {
	out := new(OnCloseResponse)
	err := c.cc.Invoke(ctx, "/proto.Node/OnClose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
type NodeServer interface {
	Init(context.Context, *InitRequest) (*Empty, error)
	OnCreate(context.Context, *OnCreateRequest) (*OnCreateResponse, error)
	OnMessage(context.Context, *OnMessageRequest) (*OnMessageResponse, error)
	OnClose(context.Context, *OnCloseRequest) (*OnCloseResponse, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Node/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_OnCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).OnCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Node/OnCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).OnCreate(ctx, req.(*OnCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Node/OnMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).OnMessage(ctx, req.(*OnMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_OnClose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnCloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).OnClose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Node/OnClose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).OnClose(ctx, req.(*OnCloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Node_Init_Handler,
		},
		{
			MethodName: "OnCreate",
			Handler:    _Node_OnCreate_Handler,
		},
		{
			MethodName: "OnMessage",
			Handler:    _Node_OnMessage_Handler,
		},
		{
			MethodName: "OnClose",
			Handler:    _Node_OnClose_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

// RuntimeHelperClient is the client API for RuntimeHelper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RuntimeHelperClient interface {
	Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Debug(ctx context.Context, in *DebugRequest, opts ...grpc.CallOption) (*Empty, error)
	EmitFlowEvent(ctx context.Context, in *EmitFlowEventRequest, opts ...grpc.CallOption) (*Empty, error)
	EmitOutput(ctx context.Context, in *EmitOutputRequest, opts ...grpc.CallOption) (*Empty, error)
	EmitError(ctx context.Context, in *EmitErrorRequest, opts ...grpc.CallOption) (*Empty, error)
	GetVaultItem(ctx context.Context, in *GetVaultItemRequest, opts ...grpc.CallOption) (*GetVaultItemResponse, error)
	GetVariable(ctx context.Context, in *GetVariableRequest, opts ...grpc.CallOption) (*GetVariableResponse, error)
	SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*Empty, error)
}

type runtimeHelperClient struct {
	cc *grpc.ClientConn
}

func NewRuntimeHelperClient(cc *grpc.ClientConn) RuntimeHelperClient {
	return &runtimeHelperClient{cc}
}

func (c *runtimeHelperClient) Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.RuntimeHelper/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHelperClient) Debug(ctx context.Context, in *DebugRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.RuntimeHelper/Debug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHelperClient) EmitFlowEvent(ctx context.Context, in *EmitFlowEventRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.RuntimeHelper/EmitFlowEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHelperClient) EmitOutput(ctx context.Context, in *EmitOutputRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.RuntimeHelper/EmitOutput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHelperClient) EmitError(ctx context.Context, in *EmitErrorRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.RuntimeHelper/EmitError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHelperClient) GetVaultItem(ctx context.Context, in *GetVaultItemRequest, opts ...grpc.CallOption) (*GetVaultItemResponse, error) {
	out := new(GetVaultItemResponse)
	err := c.cc.Invoke(ctx, "/proto.RuntimeHelper/GetVaultItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHelperClient) GetVariable(ctx context.Context, in *GetVariableRequest, opts ...grpc.CallOption) (*GetVariableResponse, error) {
	out := new(GetVariableResponse)
	err := c.cc.Invoke(ctx, "/proto.RuntimeHelper/GetVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeHelperClient) SetVariable(ctx context.Context, in *SetVariableRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.RuntimeHelper/SetVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeHelperServer is the server API for RuntimeHelper service.
type RuntimeHelperServer interface {
	Close(context.Context, *Empty) (*Empty, error)
	Debug(context.Context, *DebugRequest) (*Empty, error)
	EmitFlowEvent(context.Context, *EmitFlowEventRequest) (*Empty, error)
	EmitOutput(context.Context, *EmitOutputRequest) (*Empty, error)
	EmitError(context.Context, *EmitErrorRequest) (*Empty, error)
	GetVaultItem(context.Context, *GetVaultItemRequest) (*GetVaultItemResponse, error)
	GetVariable(context.Context, *GetVariableRequest) (*GetVariableResponse, error)
	SetVariable(context.Context, *SetVariableRequest) (*Empty, error)
}

func RegisterRuntimeHelperServer(s *grpc.Server, srv RuntimeHelperServer) {
	s.RegisterService(&_RuntimeHelper_serviceDesc, srv)
}

func _RuntimeHelper_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHelperServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RuntimeHelper/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHelperServer).Close(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHelper_Debug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHelperServer).Debug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RuntimeHelper/Debug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHelperServer).Debug(ctx, req.(*DebugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHelper_EmitFlowEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitFlowEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHelperServer).EmitFlowEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RuntimeHelper/EmitFlowEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHelperServer).EmitFlowEvent(ctx, req.(*EmitFlowEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHelper_EmitOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHelperServer).EmitOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RuntimeHelper/EmitOutput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHelperServer).EmitOutput(ctx, req.(*EmitOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHelper_EmitError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHelperServer).EmitError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RuntimeHelper/EmitError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHelperServer).EmitError(ctx, req.(*EmitErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHelper_GetVaultItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVaultItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHelperServer).GetVaultItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RuntimeHelper/GetVaultItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHelperServer).GetVaultItem(ctx, req.(*GetVaultItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHelper_GetVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHelperServer).GetVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RuntimeHelper/GetVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHelperServer).GetVariable(ctx, req.(*GetVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeHelper_SetVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeHelperServer).SetVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RuntimeHelper/SetVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeHelperServer).SetVariable(ctx, req.(*SetVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RuntimeHelper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RuntimeHelper",
	HandlerType: (*RuntimeHelperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Close",
			Handler:    _RuntimeHelper_Close_Handler,
		},
		{
			MethodName: "Debug",
			Handler:    _RuntimeHelper_Debug_Handler,
		},
		{
			MethodName: "EmitFlowEvent",
			Handler:    _RuntimeHelper_EmitFlowEvent_Handler,
		},
		{
			MethodName: "EmitOutput",
			Handler:    _RuntimeHelper_EmitOutput_Handler,
		},
		{
			MethodName: "EmitError",
			Handler:    _RuntimeHelper_EmitError_Handler,
		},
		{
			MethodName: "GetVaultItem",
			Handler:    _RuntimeHelper_GetVaultItem_Handler,
		},
		{
			MethodName: "GetVariable",
			Handler:    _RuntimeHelper_GetVariable_Handler,
		},
		{
			MethodName: "SetVariable",
			Handler:    _RuntimeHelper_SetVariable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
